services:
  - type: web
    name: indian-translator-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: translator_database
      - key: CORS_ORIGINS
        value: "*"